apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167845920
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167845920
    app.kubernetes.io/part-of: test-app-167845920
  name: java-quarkus-167845920
  namespace: 4zkyise1-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-167845920
status:
  loadBalancer: {}
